# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:7.2

pipelines:
    branches:
        development-0.0.3:
        - step: 
            name: Production
            caches:
              - composer
            script:
              - apt-get update && apt-get install -y unzip
              - apt-get install -y openssh-client
              - ssh snigdha_parastechnologies@35.203.54.160 'bash -s' < execute.sh